import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execute = promisify(execFile);

/** Compile once on the build host; the Bare WebView loads no remote assets. */
export async function buildDesktopStyles(repository: string): Promise<void> {
  const root = await mkdtemp(path.join(os.tmpdir(), "kepos-desktop-css-"));
  try {
    const require = createRequire(path.join(repository, "apps/desktop/package.json"));
    const cliPackage = require.resolve("@tailwindcss/cli/package.json");
    const output = path.join(root, "ui.css");
    await execute(process.execPath, [
      path.join(path.dirname(cliPackage), "dist/index.mjs"),
      "--input", path.join(repository, "apps/desktop/src/ui.css"),
      "--output", output,
      "--minify",
    ], { cwd: repository });
    const css = await readFile(output, "utf8");
    await writeFile(path.join(repository, "apps/desktop/src/ui-styles.ts"),
      `// Generated by scripts/build-desktop-styles.ts; edit ui.css.\nexport const desktopStyles = ${JSON.stringify(css)};\n`);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await buildDesktopStyles(fileURLToPath(new URL("..", import.meta.url)));
}
